name: Release Site

on:
  workflow_run:
    workflows: ["Build Site"]
    types:
      - completed
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    environment: 
      name: legion
      url: https://pros.cs.purdue.edu
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          # name: pros-docs.tar.gz
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Compress Artifact
        run: |
            cd pros-docs
            tar -czf ../pros-docs.tar.gz *
            cd ..

      - name: Deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ vars.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          scp: pros-docs.tar.gz => ~/pros-website/
          last_ssh: ~/pros-website/deploy.sh